### PR TITLE
fix(Redis):  refactor and gas golfing

### PR DESCRIPTION
**Pull request by n00b21337**
Same pattern and reasoning applied as here
https://github.com/ethersphere/storage-incentives/pull/159

view here
https://github.com/ethersphere/storage-incentives/blob/c5bfab1d29b06831e0a02ad9276c34cd4ef73927/src/Redistribution.sol

### CODE REVIEW

**Review by nugaon — APPROVED** [review]
would be nice to introduce corresponding prettier/solhint rules.

**Comment by n00b21337** [comment]
> would be nice to introduce corresponding prettier/solhint rules.

Not sure what is asked here, but will try to elaborate on that.
There is a prettierrc.js file with solidity rules in repos root
which uses standard solidity formatting, also I would recommend setting it as default for formating. 
If using VS code, then best is to have it used "on Save" and as default formatter, like on image below

image

**Comment by nugaon** [comment]
prettier/eslint should give at least warnings but even errors when the format of the document is not right.
it usually appears in the `problems` section in VS.
we could add an additional NPM style check command as well for this and run it in the test CI script, thereby it wouldn't be possible to merge if the code is not in the desired format.

**Comment by nugaon** [comment]
created issue about it in #169

**Comment by n00b21337** [comment]
> prettier/eslint should give at least warnings but even errors when the format of the document is not right. it usually appears in the `problems` section in VS. we could add an additional NPM style check command as well for this and run it in the test CI script, thereby it wouldn't be possible to merge if the code is not in the desired format.

yes, that is good idea.

**Comment by n00b21337** [comment]
Merged #163  and #164  into this one as they were checked and approved.

**Comment by n00b21337** [comment]
> > prettier/eslint should give at least warnings but even errors when the format of the document is not right. it usually appears in the `problems` section in VS. we could add an additional NPM style check command as well for this and run it in the test CI script, thereby it wouldn't be possible to merge if the code is not in the desired format.
> 
> yes, that is good idea.

Also, this is solved now.

**Comment by n00b21337** [comment]
closed and continued here
https://github.com/ethersphere/storage-incentives/pull/186

**Pull request closed without merging**
